### PR TITLE
initial commit for new pull request

### PR DESCRIPTION
**Pull request by stevejthorpe**
Ok - created a new app with expo minimal typescript. Edited the README with basic instructions.

### CODE REVIEW

**Comment by qaiser42** [comment]
`package-lock.json` is back :)

**Comment by qaiser42** [comment]
could it be that this version is the same as before? there are directories existing for android and ios with native code. this is the directory i get generated when i used expo with the typescript template 
Screenshot 2020-03-03 at 17 07 45

**Comment by stevejthorpe** [comment]
> could it be that this version is the same as before? there are directories existing for android and ios with native code. this is the directory i get generated when i used expo with the typescript template
> Screenshot 2020-03-03 at 17 07 45

I am using `expo init` and the minimalist with typescript template. Would you suggest another approach? `npx` and `--template react-native-template-typescript`?

**Comment by qaiser42** [comment]
I used the `expo-template-blank-typescript` template

**Comment by qaiser42** [comment]
i reckon `react-native-template-*` always gives you the native code directories for android and ios

**Pull request closed without merging**
